services:
  vue:
    container_name: vue_app
    image: ghcr.io/johnskouloudis/assignment_rid_v1_frontend:latest
    depends_on:
      spring:
        condition: service_started
    environment:
      - VITE_BACKEND_URL=spring:9090
    ports:
      - 8080:5173

  spring:
    container_name: spring_app
    image: ghcr.io/johnskouloudis/assignment_rid_v1:latest
    depends_on:
       db:
          condition: service_healthy
    environment:
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=db:5432/${DB_USERNAME:-postgres}
    ports:
      - 9090:9090

  db:
    container_name: postgres_db
    image: postgres:alpine3.20
    environment:
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 8081:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${DB_USERNAME:-postgres}
      interval: 5s
      timeout: 15s
      retries: 5

volumes:
    postgres_data:

