services:
  app:
    container_name: spring_app
    image: ghcr.io/johnskouloudis/assignment_rid_v1:latest
    depends_on:
      - db
    environment:
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=db:5432/${DB_USERNAME:-postgres}
    ports:
      - 9090:9090

  db:
    container_name: postgres_db
    image: postgres:alpine3.20
    environment:
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 8080:5432


